import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    files: ["**/*.ts", "**/*.tsx"],
    rules: {
      "no-unused-vars": "warn",
      "no-console": "warn",
      "no-debugger": "warn",
      "react-hooks/exhaustive-deps": "warn",
      "react/jsx-key": "warn",
      "react/jsx-no-duplicate-props": "warn",
      "react/jsx-no-undef": "warn",
      "react/jsx-uses-react": "warn",
      "react/jsx-uses-vars": "warn",
      "react/no-children-prop": "warn",
      "react/no-danger-with-children": "warn",
      "react/no-deprecated": "warn",
      "react/no-direct-mutation-state": "warn",
      "react/no-find-dom-node": "warn",
      "react/no-is-mounted": "warn",
      "react/no-render-return-value": "warn",
      "react/no-string-refs": "warn",
      "react/no-unescaped-entities": "warn",
      "react/no-unknown-property": "warn",
      "react/prop-types": "warn",
      "react/react-in-jsx-scope": "warn",
      "react/require-render-return": "warn",
      "react/self-closing-comp": "warn",
      "react/style-prop-object": "warn",
      "react/jsx-no-target-blank": "warn",
      "react/jsx-pascal-case": "warn",
      "react/jsx-props-no-spreading": "warn",
      "react/jsx-sort-props": "warn",
      "react/jsx-wrap-multilines": "warn",
      "react/no-access-state-in-setstate": "warn",
      "react/no-adjacent-inline-elements": "warn",
      "react/no-array-index-key": "warn",
      "react/no-children-prop": "warn",
      "react/no-danger": "warn",
      "react/no-danger-with-children": "warn",
      "react/no-deprecated": "warn",
      "react/no-did-mount-set-state": "warn",
      "react/no-did-update-set-state": "warn",
      "react/no-direct-mutation-state": "warn",
      "react/no-find-dom-node": "warn",
      "react/no-is-mounted": "warn",
      "react/no-multi-comp": "warn",
      "react/no-redundant-should-component-update": "warn",
      "react/no-render-return-value": "warn",
      "react/no-set-state": "warn",
      "react/no-string-refs": "warn",
      "react/no-this-in-sfc": "warn",
      "react/no-typos": "warn",
      "react/no-unescaped-entities": "warn",
      "react/no-unknown-property": "warn",
      "react/no-unsafe": "warn",
      "react/no-unused-prop-types": "warn",
      "react/no-unused-state": "warn",
      "react/no-will-update-set-state": "warn",
      "react/prefer-es6-class": "warn",
      "react/prefer-read-only-props": "warn",
      "react/prefer-stateless-function": "warn",
      "react/prop-types": "warn",
      "react/react-in-jsx-scope": "warn",
      "react/require-default-props": "warn",
      "react/require-optimization": "warn",
      "react/require-render-return": "warn",
      "react/self-closing-comp": "warn",
      "react/sort-comp": "warn",
      "react/sort-prop-types": "warn",
      "react/state-in-constructor": "warn",
      "react/static-property-placement": "warn",
      "react/style-prop-object": "warn",
      "react/void-dom-elements-no-children": "warn",
    },
  },
];

export default eslintConfig;
