name: LeetCode Metrics

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  leetcode-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Gerar LeetCode Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.leetcode.svg
          token: NOT_NEEDED
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Commit e Push SVG
        run: |
          git add metrics.plugin.leetcode.svg
          git diff --cached --quiet || git commit -m "Atualiza LeetCode Metrics SVG [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
